//Array
let items =[{id: 1, title: "Force of Nature: A Conservation History of Forest & Bird", author: "David Young & Naomi Arnold", year: 2024, price: 89.99, category: 1, image_url: "Images/Force-of-Nature-FB-Cover-600px-wide-72dpi.jpg", description: "The inspiring history of Forest & Bird, New Zealand's oldest independent conservation organisation for over 100 years. Beginning in 1923, Forest & Bird have been involved in all of the significant environmental campaigns of the last century, starting with efforts to protect native birds and their forest habitat, creation of many of the national parks and in recent decades efforts to protect our marine environment and attempts to tackle climate change.", pdf:"PDFs/array_1.pdf"},
    {id: 2, title: "Kākāpō: Rescued From the Brink of Extinction", author: "Alison Ballance", year: 2018, price: 49.99, category: 1, image_url: "Images/Kakapo_72.jpg", description: "New Zealand's threatened night parrot, the kākāpō, has been the focus of a remarkable conservation effort that has seen the bird's population rise from a perilous low of 51 aging birds to three times that number. Kākāpō are unique and unusual birds. Long-lived, flightless heavyweights, they only breed every two to four years, and survive on just a small number of predator-free island sanctuaries.", pdf:"PDFs/array_2.pdf"}, 
    {id: 3, title: "Geckos & Skinks: The Remarkable Lizards of Aotearoa", author: "Anna Yeoman", year: 2024, price: 59.99, category: 1, image_url: "Images/Geckos-Skinks-Final-Cover-600px-wide-72dpi.jpg", description: "The first book to tell stories about the lizards of Aotearoa New Zealand, how and where they live, and how they breed. But crucially, this book is a fascinating insight into the myriad conservation efforts that are ongoing in New Zealand, for our geckos and skinks are increasingly threatened by habitat loss and predation from pests.", pdf:"PDFs/array_3.pdf"}, 
    {id: 4, title: "Takahē: Bird of Dreams", author: "Alison Ballance", year: 2023, price: 59.99, category: 1, image_url: "Images/TAKAHE-FC-600px-wide-72dpi.jpg", description: "The inspiring story of the rediscovery and then recovery of the takahē, one of New Zealand's most intriguing native birds. Once thought extinct, in 1948 Geoffrey Orbell found a small population living in a remote valley in the Murchison Mountains of Fiordland.", pdf:"PDFs/array_4.pdf"}, 
    {id: 5, title: "Moa: The Life and Death of New Zealand's Legendary Bird", author: "Quinn Berentson", year: 2012, price: 59.99, category: 1, image_url: "Images/MOA-Cover-600-px-wide.jpg", description: "The moa were the most unusual and unique family of birds that ever lived, a clan of feathered monsters that developed in isolation for many, many millions of years. They became extinct reasonably quickly after the arrival of the Maori, and were a distant memory by the time European explorers arrived.", pdf:"PDFs/array_5.pdf"}, 
    {id: 6, title: "Field Guide to New Zealand's Native Trees", author: "John Dawson & Rob Lucas", year: 2020, price: 49.99, category: 2, image_url: "Images/54e3dcff08ffb_fieldguidetontcvr72dpi.jpg", description: "This comprehensive field guide to New Zealand's native trees is compact enough to fit in a day-pack. Illustrated with more than 1500 superb photographs, it contains detailed information on all native trees found on the main islands of New Zealand.", pdf:"PDFs/array_6.pdf"}, 
    {id: 7, title: "Fungi of Aotearoa: A Curious Forager's Field Guide", author: "Liv Sasson", year: 2023, price: 44.99, category: 2, image_url: "Images/9781761047879__00217.jpg", description: "The complete introduction to finding, identifying and using mushrooms and other fungi in New Zealand. Discover how to identify the best edible varieties, and how to cook with them, how these incredible organisms have shaped the world as we know it, and the role they are playing in modern medical and environmental research.", pdf:"PDFs/array_7.pdf"}, 
    {id: 8, title: "The Forager's Treasury: The Essential Guide to Finding and Using Wild Plants in Aotearoa", author: "Johanna Knox", year: 2021, price: 49.99, category: 2, image_url: "Images/The_20Forager_s_20Treasury.webp", description: "In the urban and rural wildernesses, there is an abundance of food just waiting to be discovered, if only you know what to look for. Foraged food is healthy, economical and sustainable, but the best part is the fun you will have finding it. This book is guaranteed to make you look at the plants around you in a different light.", pdf:"PDFs/array_8.pdf"}, 
    {id: 9, title: "Mystical Mushrooms: Discover the Magic and Folklore of Fantastic Fungi", author: "Aurora Kane", year: 2023, price: 40.99, category: 2, image_url: "Images/9781631069215.jpg", description: "Defines the beauty of mushrooms by focusing on their magical connections and symbolic meanings through folkloric tales and superstitions throughout the world. Explore the magical properties, mythological connections, and symbolic qualities of ever-intriguing fungi.", pdf:"PDFs/array_9.pdf"}, 
    {id: 10, title: "Know Your New Zealand Native Plants", author: "Lawrie Metcalf", year: 2009, price: 39.99, category: 2, image_url: "Images/9781776940363.jpg", description: "Introduces a selection of the most interesting, iconic and important New Zealand plants, spanning latitudes from subtropical to temperate, and altitudes from sea level to alpine mountaintop, describing their natural history and distinguishing features.", pdf:"PDFs/array_10.pdf"},
    {id: 11, title: "Vanishing Ice: Stories of New Zealand's Glaciers", author: "Lynley Hargreaves", year: 2022, price: 59.99, category: 3, image_url: "Images/VANISHING-ICE-cover-600px-wide-72dpi.jpg", description: "This important book tells the stories of our glaciers through the lens of human interaction, with chapters moving through time from first Māori discoverers to colonial explorers, mountaineers and modern glaciologists.", pdf:"PDFs/array_11.pdf"},
    {id: 12, title: "Kahurangi: The Nature of Kahurangi National Park and Northwest Nelson", author: "Dave Hansford", year: 2024, price: 79.99, category: 3, image_url: "Images/Kahurangi-Cover-600px-wide-72dpi.jpg", description: "Energised by ancient, complex geology and a multitude of habitats, from vast beech stands to lush coastal rainforest, from sprawling ramparts of karst and marble to extensive wetlands and estuaries, this region holds the greatest variety of plants and animals in the country.", pdf:"PDFs/array_12.pdf"},
    {id: 13, title: "Tamatea Dusky: The Remarkable Story of Fiordland's Dusky Sound", author: "Peta Carey", year: 2020, price: 69.99, category: 3, image_url: "Images/Tamatea-Dusky-600px.jpg", description: "The remarkable story of conservation and history in Fiordland's Tamatea/Dusky Sound, where ground-breaking work in predator control and species conservation has taken place over the last 50 years.", pdf:"PDFs/array_13.pdf"},
    {id: 14, title: "New Zealand North and South", author: "Craig Potton", year: 2011, price: 14.99, category: 3, image_url: "Images/54e3db1449caa_nznorthandsouth.jpg", description: "New Zealand's North and South islands are remarkable for the diversity of their landscapes and culture. The essence of the South Island lies in its wild and unspoiled mountains, glaciers, forests, rivers, lakes and fiords. The North Island, a place more modified by human hands, still surprises with the beauty of its kauri forests, steaming vents and volcanoes, and the strength of its Maori cultural traditions.", pdf:"PDFs/array_14.pdf"},
    {id: 15, title: "Not Set in Stone: The Passion and Consequence of a Mountain Life", author: "Dave Vass", year: 2023, price: 39.99, category: 3, image_url: "Images/Not-Set-In-Stone-cover-600-px-wide.jpg", description: "Between the 1980s and 2015, Dave Vass became one of New Zealand's leading mountaineers. Here he recounts the beginning of his outdoor life caving and rafting, before turning to climbing and the hard routes on Mt Aspiring National Park and Darran Mountains in Fiordland.", pdf:"PDFs/array_15.pdf"},
    ];

let categories = [ {id: 1, category: "Fauna"},
    {id: 2, category: "Flora"},
    {id: 3, category: "Terra"},  
    ];


//Overlay menu
function openNav() {
    document.getElementById("myNav").style.display = "block";
}
function closeNav() {
    document.getElementById("myNav").style.display = "none";
}
